### ISSUE TITLE
你好， 请问这个代码是手写的， 还是通过工具转的啊？ 

### ISSUE THREAD

**Issue by xukaifu** [jerexyz/weixin-jssdk#1]
我有一些别的第三方代码， 也是跟这个很像， 需要转成commonjs版本， 所以请教一下。

**Comment by jerexyz** [comment]
拿官方的代码修改的，用工具的话 ， 要看 第三方是什么样的 ， 具体情况  具体处理。

**Comment by xukaifu** [comment]
感谢， 这么快就回复了。 

demo ： http://jspay.wiipay.cn/h5pay.html
我用到了wiipay这个组件， 但是官方不支持commonJS， 我也不知道怎么转， 我看它代码主要是
http://jspay.oss-cn-hangzhou.aliyuncs.com/public/jspay/js/wpay-jspay.1.3.js

不知道这样的要怎么转？ 
请问有什么工具或者方法能指点一下吗， 因为代码混淆过， 要读懂每一行感觉有点难， 而且改还怕改错。

**Comment by jerexyz** [comment]
抱歉  我也看不懂
